export const actions = {
    PATHS_ADD: "PATHS_ADD",
    PATHS_CYCLE_SELECTION: "PATHS_CYCLE_SELECTION",
    PATHS_CYCLE_SELECTION_RV: "PATHS_CYCLE_SELECTION_RV",
    GRID_CYCLE_SIZE: "GRID_CYCLE_SIZE",
    GRID_CYCLE_SIZE_RV: "GRID_CYCLE_SIZE_RV"
};

