export const actions = {
    MODE_PUSH_PATH_SELECT_SEGMENT: "MODE_PUSH_PATH_SELECT_SEGMENT",
    MODE_PUSH_PATH_SELECT_POINT: "MODE_PUSH_PATH_SELECT_POINT",
    MODE_POP: "MODE_POP",
    GRID_CYCLE_SIZE: "GRID_CYCLE_SIZE",
    GRID_CYCLE_SIZE_RV: "GRID_CYCLE_SIZE_RV",
    SHAPES_CYCLE_SELECTION: "SHAPES_CYCLE_SELECTION",
    SHAPES_CYCLE_SELECTION_RV: "SHAPES_CYCLE_SELECTION_RV",
    SHAPES_ADD_PATH: "SHAPES_ADD_PATH",
    PATH_CYCLE_SEGMENT_SELECTION: "PATH_CYCLE_SEGMENT_SELECTION",
    PATH_CYCLE_SEGMENT_SELECTION_RV: "PATH_CYCLE_SEGMENT_SELECTION_RV",
    PATH_ADD_SEGMENT: "PATH_ADD_SEGMENT",
    POINT_MOVE_UP: "POINT_MOVE_UP",
    POINT_MOVE_DOWN: "POINT_MOVE_DOWN",
    POINT_MOVE_LEFT: "POINT_MOVE_LEFT",
    POINT_MOVE_RIGHT: "POINT_MOVE_RIGHT",
};

export const modes = {
    TOP_DEFAULT: "TOP_DEFAULT",
    PATH_SELECT_SEGMENT: "PATH_SELECT_SEGMENT",
    PATH_SELECT_POINT: "PATH_SELECT_POINT",
    PATH_EDIT_POINT: "PATH_EDIT_POINT",
};
