export const actions = {
    MODE_PUSH_PATH_SELECT_SEGMENT: "MODE_PUSH_PATH_SELECT_SEGMENT",
    MODE_POP: "MODE_POP",
    GRID_CYCLE_SIZE: "GRID_CYCLE_SIZE",
    GRID_CYCLE_SIZE_RV: "GRID_CYCLE_SIZE_RV",
    PATHS_ADD: "PATHS_ADD",
    PATHS_CYCLE_SELECTION: "PATHS_CYCLE_SELECTION",
    PATHS_CYCLE_SELECTION_RV: "PATHS_CYCLE_SELECTION_RV",
    PATH_CYCLE_SEGMENT_SELECTION: "PATH_CYCLE_SEGMENT_SELECTION",
    PATH_CYCLE_SEGMENT_SELECTION_RV: "PATH_CYCLE_SEGMENT_SELECTION_RV",
    PATH_ADD_SEGMENT: "PATH_ADD_SEGMENT",
};

export const modes = {
    TOP_DEFAULT: "TOP_DEFAULT",
    PATH_SELECT_SEGMENT: "PATH_SELECT_SEGMENT",
    PATH_SELECT_POINT: "PATH_SELECT_POINT",
    PATH_EDIT_POINT: "PATH_EDIT_POINT",
};
